name: Docker image for node example

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username ${{ secrets.USER }} --password ${{ secrets.PAT }}
          docker build . --tag ghcr.io/${{ secrets.USER }}/node-example:latest
          docker push ghcr.io/${{ secrets.USER }}/node-example:latest
          
