name: Docker Publish

on:
  push:
    branches:
      - main # Change this to your main branch name, e.g., master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/node-example:${{ github.sha }} .
        docker push docker.pkg.github.com/${{ github.repository }}/node-example:${{ github.sha }}
